let tickets = [
  {
    id: 1,
    from: "Cairo",
    to: "Hurghada",
    typeOfTrip: "round trip",
    passengerNumbers: "4",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "5:48AM",
    timeTo: "9:01AM",
    time: "3 hr 13 min",
    price: 459,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: "direct",
  },
  {
    id: 2,
    from: "Dakhla Oasis",
    to: "Cairo",
    typeOfTrip: "round trip",
    passengerNumbers: "8",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "5:06AM",
    timeTo: "8:52AM",
    time: "3 hr 46 min",
    price: 312,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: "direct",
  },
  {
    id: 3,
    from: "Hurghada",
    to: "Cairo",
    typeOfTrip: "one way",
    passengerNumbers: "2",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "1:07PM",
    timeTo: "4:47PM",
    time: "3 hr 40 min",
    price: 549,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: 1,
  },
  {
    id: 4,
    from: "Port Said",
    to: "El Arish",
    typeOfTrip: "round trip",
    passengerNumbers: "9",
    class: "business",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "8:18AM",
    timeTo: "10:44AM",
    time: "2 hr 26 min",
    price: 394,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: "direct",
  },
  {
    id: 5,
    from: "Luxor",
    to: "Hurghada",
    typeOfTrip: "round trip",
    passengerNumbers: "6",
    class: "premium",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "8:48PM",
    timeTo: "12:12AM",
    time: "3 hr 24 min",
    price: 517,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: "direct",
  },
  {
    id: 6,
    from: "Marsa Alam",
    to: "Aswan",
    typeOfTrip: "round trip",
    passengerNumbers: "1",
    class: "premium",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "2:12AM",
    timeTo: "5:24AM",
    time: "3 hr 12 min",
    price: 595,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: 1,
  },
  {
    id: 7,
    from: "Cairo",
    to: "El Arish",
    typeOfTrip: "one way",
    passengerNumbers: "4",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "4:48AM",
    timeTo: "7:10AM",
    time: "2 hr 22 min",
    price: 403,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 8,
    from: "Taba",
    to: "Luxor",
    typeOfTrip: "round trip",
    passengerNumbers: "6",
    class: "business",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "9:36PM",
    timeTo: "11:51PM",
    time: "2 hr 15 min",
    price: 329,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: 1,
  },
  {
    id: 9,
    from: "Abu Simbel",
    to: "Alexandria",
    typeOfTrip: "one way",
    passengerNumbers: "5",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "2:35PM",
    timeTo: "5:01PM",
    time: "2 hr 26 min",
    price: 301,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: 1,
  },
  {
    id: 10,
    from: "El Arish",
    to: "Hurghada",
    typeOfTrip: "one way",
    passengerNumbers: "3",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "6:03PM",
    timeTo: "9:57PM",
    time: "3 hr 54 min",
    price: 554,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: 1,
  },
  {
    id: 11,
    from: "Dakhla Oasis",
    to: "Luxor",
    typeOfTrip: "one way",
    passengerNumbers: "2",
    class: "economy",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "6:34AM",
    timeTo: "10:00AM",
    time: "3 hr 26 min",
    price: 567,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: "direct",
  },
  {
    id: 12,
    from: "Abu Simbel",
    to: "Sharm El Sheikh",
    typeOfTrip: "one way",
    passengerNumbers: "10",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "7:55AM",
    timeTo: "9:02AM",
    time: "1 hr 7 min",
    price: 546,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: "direct",
  },
  {
    id: 13,
    from: "Dakhla Oasis",
    to: "Cairo",
    typeOfTrip: "round trip",
    passengerNumbers: "10",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "7:57AM",
    timeTo: "11:30AM",
    time: "3 hr 33 min",
    price: 444,
    vat: 14,
    airline: "Adeal",
    numberOfStops: 1,
  },
  {
    id: 14,
    from: "Abu Simbel",
    to: "Alexandria",
    typeOfTrip: "one way",
    passengerNumbers: "1",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "7:37PM",
    timeTo: "11:25PM",
    time: "3 hr 48 min",
    price: 441,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: "direct",
  },
  {
    id: 15,
    from: "El Arish",
    to: "Dakhla Oasis",
    typeOfTrip: "one way",
    passengerNumbers: "2",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "5:53AM",
    timeTo: "8:57AM",
    time: "3 hr 4 min",
    price: 384,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: "direct",
  },
  {
    id: 16,
    from: "El Arish",
    to: "Taba",
    typeOfTrip: "round trip",
    passengerNumbers: "8",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "2:10AM",
    timeTo: "6:07AM",
    time: "3 hr 57 min",
    price: 539,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: 1,
  },
  {
    id: 17,
    from: "Hurghada",
    to: "Aswan",
    typeOfTrip: "one way",
    passengerNumbers: "9",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "3:44PM",
    timeTo: "5:14PM",
    time: "1 hr 30 min",
    price: 371,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: 1,
  },
  {
    id: 18,
    from: "Marsa Alam",
    to: "Sohag",
    typeOfTrip: "round trip",
    passengerNumbers: "7",
    class: "business",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "3:34AM",
    timeTo: "5:53AM",
    time: "2 hr 19 min",
    price: 391,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: 1,
  },
  {
    id: 19,
    from: "Marsa Alam",
    to: "Taba",
    typeOfTrip: "one way",
    passengerNumbers: "3",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "7:04AM",
    timeTo: "9:20AM",
    time: "2 hr 16 min",
    price: 511,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: "direct",
  },
  {
    id: 20,
    from: "Luxor",
    to: "Taba",
    typeOfTrip: "round trip",
    passengerNumbers: "2",
    class: "premium",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "2:22AM",
    timeTo: "6:13AM",
    time: "3 hr 51 min",
    price: 470,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: "direct",
  },
  {
    id: 21,
    from: "Port Said",
    to: "Sohag",
    typeOfTrip: "round trip",
    passengerNumbers: "7",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "5:22AM",
    timeTo: "9:04AM",
    time: "3 hr 42 min",
    price: 577,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: 1,
  },
  {
    id: 22,
    from: "Dakhla Oasis",
    to: "Sharm El Sheikh",
    typeOfTrip: "round trip",
    passengerNumbers: "3",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "11:28PM",
    timeTo: "2:50AM",
    time: "3 hr 22 min",
    price: 303,
    vat: 14,
    airline: "Adeal",
    numberOfStops: 1,
  },
  {
    id: 23,
    from: "Luxor",
    to: "Cairo",
    typeOfTrip: "one way",
    passengerNumbers: "2",
    class: "economy",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "6:25AM",
    timeTo: "10:19AM",
    time: "3 hr 54 min",
    price: 352,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: 1,
  },
  {
    id: 24,
    from: "Dakhla Oasis",
    to: "El Arish",
    typeOfTrip: "one way",
    passengerNumbers: "2",
    class: "premium",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "7:35AM",
    timeTo: "10:28AM",
    time: "2 hr 53 min",
    price: 530,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: "direct",
  },
  {
    id: 25,
    from: "Luxor",
    to: "Port Said",
    typeOfTrip: "round trip",
    passengerNumbers: "6",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "2:00AM",
    timeTo: "5:17AM",
    time: "3 hr 17 min",
    price: 495,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: 1,
  },
  {
    id: 26,
    from: "Aswan",
    to: "Alexandria",
    typeOfTrip: "round trip",
    passengerNumbers: "7",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "12:26PM",
    timeTo: "3:47PM",
    time: "3 hr 21 min",
    price: 507,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: 1,
  },
  {
    id: 27,
    from: "Luxor",
    to: "Abu Simbel",
    typeOfTrip: "one way",
    passengerNumbers: "5",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "4:30AM",
    timeTo: "6:41AM",
    time: "2 hr 11 min",
    price: 524,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: 1,
  },
  {
    id: 28,
    from: "Luxor",
    to: "Hurghada",
    typeOfTrip: "round trip",
    passengerNumbers: "9",
    class: "business",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "3:26PM",
    timeTo: "4:46PM",
    time: "1 hr 20 min",
    price: 416,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: "direct",
  },
  {
    id: 29,
    from: "Alexandria",
    to: "Aswan",
    typeOfTrip: "round trip",
    passengerNumbers: "8",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "10:02AM",
    timeTo: "11:38AM",
    time: "1 hr 36 min",
    price: 401,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: "direct",
  },
  {
    id: 30,
    from: "Cairo",
    to: "El Arish",
    typeOfTrip: "one way",
    passengerNumbers: "2",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "3:07AM",
    timeTo: "6:56AM",
    time: "3 hr 49 min",
    price: 533,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: "direct",
  },
  {
    id: 31,
    from: "Cairo",
    to: "Alexandria",
    typeOfTrip: "round trip",
    passengerNumbers: "9",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "4:30PM",
    timeTo: "6:44PM",
    time: "2 hr 14 min",
    price: 376,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: 1,
  },
  {
    id: 32,
    from: "Luxor",
    to: "Sharm El Sheikh",
    typeOfTrip: "round trip",
    passengerNumbers: "2",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "5:29PM",
    timeTo: "7:19PM",
    time: "1 hr 50 min",
    price: 561,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: "direct",
  },
  {
    id: 33,
    from: "Marsa Alam",
    to: "Port Said",
    typeOfTrip: "round trip",
    passengerNumbers: "10",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "5:07PM",
    timeTo: "8:51PM",
    time: "3 hr 44 min",
    price: 485,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: 1,
  },
  {
    id: 34,
    from: "Marsa Alam",
    to: "Port Said",
    typeOfTrip: "one way",
    passengerNumbers: "6",
    class: "business",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "9:10AM",
    timeTo: "11:15AM",
    time: "2 hr 5 min",
    price: 508,
    vat: 14,
    airline: "Adeal",
    numberOfStops: 1,
  },
  {
    id: 35,
    from: "El Arish",
    to: "Abu Simbel",
    typeOfTrip: "one way",
    passengerNumbers: "1",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "8:39AM",
    timeTo: "11:04AM",
    time: "2 hr 25 min",
    price: 381,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 36,
    from: "Alexandria",
    to: "Sohag",
    typeOfTrip: "round trip",
    passengerNumbers: "3",
    class: "economy",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "5:26AM",
    timeTo: "6:40AM",
    time: "1 hr 14 min",
    price: 538,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: 1,
  },
  {
    id: 37,
    from: "El Arish",
    to: "Sharm El Sheikh",
    typeOfTrip: "round trip",
    passengerNumbers: "10",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "1:59PM",
    timeTo: "4:20PM",
    time: "2 hr 21 min",
    price: 352,
    vat: 14,
    airline: "Adeal",
    numberOfStops: 1,
  },
  {
    id: 38,
    from: "Sohag",
    to: "Sharm El Sheikh",
    typeOfTrip: "one way",
    passengerNumbers: "8",
    class: "business",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "7:53AM",
    timeTo: "10:15AM",
    time: "2 hr 22 min",
    price: 481,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: 1,
  },
  {
    id: 39,
    from: "Luxor",
    to: "Cairo",
    typeOfTrip: "round trip",
    passengerNumbers: "7",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "1:54AM",
    timeTo: "3:39AM",
    time: "1 hr 45 min",
    price: 330,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: "direct",
  },
  {
    id: 40,
    from: "Sharm El Sheikh",
    to: "Hurghada",
    typeOfTrip: "one way",
    passengerNumbers: "2",
    class: "business",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "7:07PM",
    timeTo: "9:14PM",
    time: "2 hr 7 min",
    price: 563,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: 1,
  },
  {
    id: 41,
    from: "Sharm El Sheikh",
    to: "Luxor",
    typeOfTrip: "one way",
    passengerNumbers: "10",
    class: "premium",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "3:34AM",
    timeTo: "6:28AM",
    time: "2 hr 54 min",
    price: 369,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: 1,
  },
  {
    id: 42,
    from: "Dakhla Oasis",
    to: "Aswan",
    typeOfTrip: "round trip",
    passengerNumbers: "7",
    class: "economy",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "2:15PM",
    timeTo: "6:14PM",
    time: "3 hr 59 min",
    price: 580,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: 1,
  },
  {
    id: 43,
    from: "El Arish",
    to: "Marsa Alam",
    typeOfTrip: "one way",
    passengerNumbers: "5",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "12:35AM",
    timeTo: "3:09AM",
    time: "2 hr 34 min",
    price: 544,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: "direct",
  },
  {
    id: 44,
    from: "Sohag",
    to: "Sharm El Sheikh",
    typeOfTrip: "round trip",
    passengerNumbers: "1",
    class: "business",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "10:45AM",
    timeTo: "1:28PM",
    time: "2 hr 43 min",
    price: 532,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: "direct",
  },
  {
    id: 45,
    from: "Port Said",
    to: "Marsa Alam",
    typeOfTrip: "one way",
    passengerNumbers: "3",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "4:46AM",
    timeTo: "7:18AM",
    time: "2 hr 32 min",
    price: 501,
    vat: 14,
    airline: "Adeal",
    numberOfStops: 1,
  },
  {
    id: 46,
    from: "Cairo",
    to: "Alexandria",
    typeOfTrip: "one way",
    passengerNumbers: "10",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "3:04PM",
    timeTo: "4:12PM",
    time: "1 hr 8 min",
    price: 500,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: 1,
  },
  {
    id: 47,
    from: "Hurghada",
    to: "El Arish",
    typeOfTrip: "one way",
    passengerNumbers: "1",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "10:14AM",
    timeTo: "12:08PM",
    time: "1 hr 54 min",
    price: 593,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 48,
    from: "Hurghada",
    to: "Sohag",
    typeOfTrip: "round trip",
    passengerNumbers: "5",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "6:06AM",
    timeTo: "8:03AM",
    time: "1 hr 57 min",
    price: 468,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 49,
    from: "Sharm El Sheikh",
    to: "Abu Simbel",
    typeOfTrip: "round trip",
    passengerNumbers: "6",
    class: "premium",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "8:15AM",
    timeTo: "9:44AM",
    time: "1 hr 29 min",
    price: 413,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: 1,
  },
  {
    id: 50,
    from: "Aswan",
    to: "Marsa Alam",
    typeOfTrip: "one way",
    passengerNumbers: "3",
    class: "premium",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "9:33AM",
    timeTo: "11:41AM",
    time: "2 hr 8 min",
    price: 418,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 51,
    from: "Alexandria",
    to: "Taba",
    typeOfTrip: "round trip",
    passengerNumbers: "5",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "12:59AM",
    timeTo: "2:52AM",
    time: "1 hr 53 min",
    price: 424,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: 1,
  },
  {
    id: 52,
    from: "Marsa Alam",
    to: "Dakhla Oasis",
    typeOfTrip: "one way",
    passengerNumbers: "9",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "4:33AM",
    timeTo: "7:01AM",
    time: "2 hr 28 min",
    price: 592,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: "direct",
  },
  {
    id: 53,
    from: "Abu Simbel",
    to: "Aswan",
    typeOfTrip: "one way",
    passengerNumbers: "1",
    class: "premium",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "11:53AM",
    timeTo: "2:40PM",
    time: "2 hr 47 min",
    price: 507,
    vat: 14,
    airline: "Adeal",
    numberOfStops: 1,
  },
  {
    id: 54,
    from: "Sohag",
    to: "Sharm El Sheikh",
    typeOfTrip: "one way",
    passengerNumbers: "6",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "12:39AM",
    timeTo: "3:48AM",
    time: "3 hr 9 min",
    price: 320,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: 1,
  },
  {
    id: 55,
    from: "Port Said",
    to: "Hurghada",
    typeOfTrip: "round trip",
    passengerNumbers: "9",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "10:30PM",
    timeTo: "2:01AM",
    time: "3 hr 31 min",
    price: 440,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: "direct",
  },
  {
    id: 56,
    from: "Taba",
    to: "El Arish",
    typeOfTrip: "round trip",
    passengerNumbers: "1",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "12:42PM",
    timeTo: "3:44PM",
    time: "3 hr 2 min",
    price: 424,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: 1,
  },
  {
    id: 57,
    from: "Taba",
    to: "Dakhla Oasis",
    typeOfTrip: "one way",
    passengerNumbers: "4",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "10:28AM",
    timeTo: "12:59PM",
    time: "2 hr 31 min",
    price: 483,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: 1,
  },
  {
    id: 58,
    from: "Sharm El Sheikh",
    to: "Abu Simbel",
    typeOfTrip: "one way",
    passengerNumbers: "8",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "9:29AM",
    timeTo: "12:40PM",
    time: "3 hr 11 min",
    price: 402,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: "direct",
  },
  {
    id: 59,
    from: "Port Said",
    to: "Taba",
    typeOfTrip: "round trip",
    passengerNumbers: "10",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "3:49PM",
    timeTo: "4:51PM",
    time: "1 hr 2 min",
    price: 485,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: "direct",
  },
  {
    id: 60,
    from: "Cairo",
    to: "Marsa Alam",
    typeOfTrip: "one way",
    passengerNumbers: "6",
    class: "business",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "3:57AM",
    timeTo: "6:29AM",
    time: "2 hr 32 min",
    price: 600,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: "direct",
  },
  {
    id: 61,
    from: "Marsa Alam",
    to: "Abu Simbel",
    typeOfTrip: "round trip",
    passengerNumbers: "3",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "11:15AM",
    timeTo: "3:12PM",
    time: "3 hr 57 min",
    price: 578,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: "direct",
  },
  {
    id: 62,
    from: "Cairo",
    to: "Hurghada",
    typeOfTrip: "one way",
    passengerNumbers: "4",
    class: "premium",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "11:22AM",
    timeTo: "3:14PM",
    time: "3 hr 52 min",
    price: 331,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: "direct",
  },
  {
    id: 63,
    from: "El Arish",
    to: "Cairo",
    typeOfTrip: "one way",
    passengerNumbers: "10",
    class: "premium",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "3:51PM",
    timeTo: "7:39PM",
    time: "3 hr 48 min",
    price: 508,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: 1,
  },
  {
    id: 64,
    from: "Hurghada",
    to: "Marsa Alam",
    typeOfTrip: "round trip",
    passengerNumbers: "8",
    class: "business",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "1:43PM",
    timeTo: "5:06PM",
    time: "3 hr 23 min",
    price: 437,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: "direct",
  },
  {
    id: 65,
    from: "Sharm El Sheikh",
    to: "Marsa Alam",
    typeOfTrip: "one way",
    passengerNumbers: "8",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "11:43PM",
    timeTo: "12:54AM",
    time: "1 hr 11 min",
    price: 489,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: "direct",
  },
  {
    id: 66,
    from: "Taba",
    to: "Abu Simbel",
    typeOfTrip: "round trip",
    passengerNumbers: "8",
    class: "economy",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "2:40PM",
    timeTo: "6:33PM",
    time: "3 hr 53 min",
    price: 348,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: "direct",
  },
  {
    id: 67,
    from: "El Arish",
    to: "Aswan",
    typeOfTrip: "one way",
    passengerNumbers: "6",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "6:54PM",
    timeTo: "8:23PM",
    time: "1 hr 29 min",
    price: 505,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: "direct",
  },
  {
    id: 68,
    from: "Port Said",
    to: "Alexandria",
    typeOfTrip: "one way",
    passengerNumbers: "3",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "12:45AM",
    timeTo: "2:41AM",
    time: "1 hr 56 min",
    price: 544,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: 1,
  },
  {
    id: 69,
    from: "Sohag",
    to: "Abu Simbel",
    typeOfTrip: "round trip",
    passengerNumbers: "8",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "8:25AM",
    timeTo: "10:27AM",
    time: "2 hr 2 min",
    price: 525,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: "direct",
  },
  {
    id: 70,
    from: "Abu Simbel",
    to: "Hurghada",
    typeOfTrip: "round trip",
    passengerNumbers: "5",
    class: "premium",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "1:52PM",
    timeTo: "4:44PM",
    time: "2 hr 52 min",
    price: 475,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: 1,
  },
  {
    id: 71,
    from: "Sohag",
    to: "Abu Simbel",
    typeOfTrip: "round trip",
    passengerNumbers: "2",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "3:37AM",
    timeTo: "6:14AM",
    time: "2 hr 37 min",
    price: 359,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: "direct",
  },
  {
    id: 72,
    from: "Sharm El Sheikh",
    to: "Alexandria",
    typeOfTrip: "round trip",
    passengerNumbers: "1",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "3:09AM",
    timeTo: "6:38AM",
    time: "3 hr 29 min",
    price: 410,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 73,
    from: "Sohag",
    to: "Marsa Alam",
    typeOfTrip: "one way",
    passengerNumbers: "4",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "12:45AM",
    timeTo: "2:21AM",
    time: "1 hr 36 min",
    price: 337,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: "direct",
  },
  {
    id: 74,
    from: "Marsa Alam",
    to: "Abu Simbel",
    typeOfTrip: "round trip",
    passengerNumbers: "1",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "7:53AM",
    timeTo: "11:10AM",
    time: "3 hr 17 min",
    price: 429,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: 1,
  },
  {
    id: 75,
    from: "Sharm El Sheikh",
    to: "Port Said",
    typeOfTrip: "one way",
    passengerNumbers: "3",
    class: "premium",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "5:24PM",
    timeTo: "9:20PM",
    time: "3 hr 56 min",
    price: 556,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 76,
    from: "Alexandria",
    to: "Dakhla Oasis",
    typeOfTrip: "one way",
    passengerNumbers: "3",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "4:47AM",
    timeTo: "6:41AM",
    time: "1 hr 54 min",
    price: 584,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: 1,
  },
  {
    id: 77,
    from: "Sohag",
    to: "Cairo",
    typeOfTrip: "one way",
    passengerNumbers: "6",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "11:28PM",
    timeTo: "1:58AM",
    time: "2 hr 30 min",
    price: 338,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: "direct",
  },
  {
    id: 78,
    from: "Hurghada",
    to: "Port Said",
    typeOfTrip: "one way",
    passengerNumbers: "7",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "9:48PM",
    timeTo: "12:11AM",
    time: "2 hr 23 min",
    price: 600,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: 1,
  },
  {
    id: 79,
    from: "Sohag",
    to: "Alexandria",
    typeOfTrip: "one way",
    passengerNumbers: "1",
    class: "business",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "2:25PM",
    timeTo: "5:40PM",
    time: "3 hr 15 min",
    price: 454,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: "direct",
  },
  {
    id: 80,
    from: "Taba",
    to: "El Arish",
    typeOfTrip: "round trip",
    passengerNumbers: "5",
    class: "business",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "12:16PM",
    timeTo: "2:01PM",
    time: "1 hr 45 min",
    price: 459,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: "direct",
  },
  {
    id: 81,
    from: "Marsa Alam",
    to: "Luxor",
    typeOfTrip: "one way",
    passengerNumbers: "1",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "12:20AM",
    timeTo: "3:50AM",
    time: "3 hr 30 min",
    price: 530,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: 1,
  },
  {
    id: 82,
    from: "Abu Simbel",
    to: "Port Said",
    typeOfTrip: "one way",
    passengerNumbers: "10",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "9:12AM",
    timeTo: "12:26PM",
    time: "3 hr 14 min",
    price: 462,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 83,
    from: "Marsa Alam",
    to: "Alexandria",
    typeOfTrip: "one way",
    passengerNumbers: "1",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "1:42PM",
    timeTo: "3:44PM",
    time: "2 hr 2 min",
    price: 439,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: "direct",
  },
  {
    id: 84,
    from: "Cairo",
    to: "Alexandria",
    typeOfTrip: "one way",
    passengerNumbers: "7",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "8:42AM",
    timeTo: "12:36PM",
    time: "3 hr 54 min",
    price: 412,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: 1,
  },
  {
    id: 85,
    from: "Luxor",
    to: "Cairo",
    typeOfTrip: "one way",
    passengerNumbers: "10",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "5:22PM",
    timeTo: "8:01PM",
    time: "2 hr 39 min",
    price: 495,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: "direct",
  },
  {
    id: 86,
    from: "El Arish",
    to: "Hurghada",
    typeOfTrip: "round trip",
    passengerNumbers: "6",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "10:24AM",
    timeTo: "1:48PM",
    time: "3 hr 24 min",
    price: 481,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: 1,
  },
  {
    id: 87,
    from: "Hurghada",
    to: "Taba",
    typeOfTrip: "round trip",
    passengerNumbers: "10",
    class: "business",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "5:00AM",
    timeTo: "6:44AM",
    time: "1 hr 44 min",
    price: 413,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: 1,
  },
  {
    id: 88,
    from: "Taba",
    to: "Dakhla Oasis",
    typeOfTrip: "round trip",
    passengerNumbers: "1",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "1:48PM",
    timeTo: "4:51PM",
    time: "3 hr 3 min",
    price: 382,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: "direct",
  },
  {
    id: 89,
    from: "Sharm El Sheikh",
    to: "Sohag",
    typeOfTrip: "one way",
    passengerNumbers: "1",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "5:00PM",
    timeTo: "8:51PM",
    time: "3 hr 51 min",
    price: 300,
    vat: 14,
    airline: "Adeal",
    numberOfStops: 1,
  },
  {
    id: 90,
    from: "Aswan",
    to: "Cairo",
    typeOfTrip: "round trip",
    passengerNumbers: "7",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "2:38AM",
    timeTo: "5:12AM",
    time: "2 hr 34 min",
    price: 512,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: "direct",
  },
  {
    id: 91,
    from: "Marsa Alam",
    to: "Alexandria",
    typeOfTrip: "one way",
    passengerNumbers: "10",
    class: "economy",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "4:55AM",
    timeTo: "8:47AM",
    time: "3 hr 52 min",
    price: 400,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: "direct",
  },
  {
    id: 92,
    from: "El Arish",
    to: "Aswan",
    typeOfTrip: "one way",
    passengerNumbers: "5",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "4:19AM",
    timeTo: "6:08AM",
    time: "1 hr 49 min",
    price: 504,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 93,
    from: "Marsa Alam",
    to: "El Arish",
    typeOfTrip: "round trip",
    passengerNumbers: "3",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "3:03PM",
    timeTo: "6:53PM",
    time: "3 hr 50 min",
    price: 485,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 94,
    from: "El Arish",
    to: "Marsa Alam",
    typeOfTrip: "round trip",
    passengerNumbers: "9",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "4:18PM",
    timeTo: "7:42PM",
    time: "3 hr 24 min",
    price: 468,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: "direct",
  },
  {
    id: 95,
    from: "Sohag",
    to: "Port Said",
    typeOfTrip: "round trip",
    passengerNumbers: "2",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "11:57PM",
    timeTo: "1:00AM",
    time: "1 hr 3 min",
    price: 562,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 96,
    from: "Hurghada",
    to: "Cairo",
    typeOfTrip: "round trip",
    passengerNumbers: "5",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "4:31PM",
    timeTo: "7:20PM",
    time: "2 hr 49 min",
    price: 424,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 97,
    from: "Abu Simbel",
    to: "Taba",
    typeOfTrip: "one way",
    passengerNumbers: "10",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "2:35AM",
    timeTo: "4:32AM",
    time: "1 hr 57 min",
    price: 345,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: "direct",
  },
  {
    id: 98,
    from: "Dakhla Oasis",
    to: "Cairo",
    typeOfTrip: "round trip",
    passengerNumbers: "4",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "11:36PM",
    timeTo: "1:08AM",
    time: "1 hr 32 min",
    price: 307,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: "direct",
  },
  {
    id: 99,
    from: "Dakhla Oasis",
    to: "Taba",
    typeOfTrip: "round trip",
    passengerNumbers: "10",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "2:36PM",
    timeTo: "6:26PM",
    time: "3 hr 50 min",
    price: 510,
    vat: 14,
    airline: "Adeal",
    numberOfStops: 1,
  },
  {
    id: 100,
    from: "El Arish",
    to: "Dakhla Oasis",
    typeOfTrip: "one way",
    passengerNumbers: "2",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "5:10AM",
    timeTo: "7:35AM",
    time: "2 hr 25 min",
    price: 419,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: 1,
  },
  {
    id: 101,
    from: "Luxor",
    to: "Sharm El Sheikh",
    typeOfTrip: "one way",
    passengerNumbers: "2",
    class: "economy",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "2:56PM",
    timeTo: "4:49PM",
    time: "1 hr 53 min",
    price: 589,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: "direct",
  },
  {
    id: 102,
    from: "Abu Simbel",
    to: "Sharm El Sheikh",
    typeOfTrip: "round trip",
    passengerNumbers: "4",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "1:22PM",
    timeTo: "5:19PM",
    time: "3 hr 57 min",
    price: 330,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 103,
    from: "Hurghada",
    to: "Port Said",
    typeOfTrip: "one way",
    passengerNumbers: "5",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "9:50AM",
    timeTo: "12:52PM",
    time: "3 hr 2 min",
    price: 338,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: "direct",
  },
  {
    id: 104,
    from: "Port Said",
    to: "Marsa Alam",
    typeOfTrip: "round trip",
    passengerNumbers: "10",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "1:56AM",
    timeTo: "4:11AM",
    time: "2 hr 15 min",
    price: 306,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: "direct",
  },
  {
    id: 105,
    from: "Cairo",
    to: "Alexandria",
    typeOfTrip: "one way",
    passengerNumbers: "8",
    class: "business",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "5:23PM",
    timeTo: "9:04PM",
    time: "3 hr 41 min",
    price: 504,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 106,
    from: "Abu Simbel",
    to: "Sohag",
    typeOfTrip: "round trip",
    passengerNumbers: "8",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "7:14PM",
    timeTo: "11:08PM",
    time: "3 hr 54 min",
    price: 528,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: "direct",
  },
  {
    id: 107,
    from: "Marsa Alam",
    to: "Hurghada",
    typeOfTrip: "round trip",
    passengerNumbers: "8",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "4:18PM",
    timeTo: "6:04PM",
    time: "1 hr 46 min",
    price: 423,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: 1,
  },
  {
    id: 108,
    from: "Cairo",
    to: "El Arish",
    typeOfTrip: "one way",
    passengerNumbers: "7",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "6:15PM",
    timeTo: "8:15PM",
    time: "2 hr 0 min",
    price: 561,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: 1,
  },
  {
    id: 109,
    from: "Dakhla Oasis",
    to: "Taba",
    typeOfTrip: "round trip",
    passengerNumbers: "9",
    class: "premium",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "11:51PM",
    timeTo: "1:50AM",
    time: "1 hr 59 min",
    price: 385,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: 1,
  },
  {
    id: 110,
    from: "Marsa Alam",
    to: "Port Said",
    typeOfTrip: "one way",
    passengerNumbers: "10",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "9:55AM",
    timeTo: "11:57AM",
    time: "2 hr 2 min",
    price: 413,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: "direct",
  },
  {
    id: 111,
    from: "Dakhla Oasis",
    to: "Taba",
    typeOfTrip: "round trip",
    passengerNumbers: "2",
    class: "business",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "12:12AM",
    timeTo: "2:24AM",
    time: "2 hr 12 min",
    price: 361,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: 1,
  },
  {
    id: 112,
    from: "Marsa Alam",
    to: "Taba",
    typeOfTrip: "round trip",
    passengerNumbers: "2",
    class: "premium",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "6:18AM",
    timeTo: "9:44AM",
    time: "3 hr 26 min",
    price: 557,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: "direct",
  },
  {
    id: 113,
    from: "El Arish",
    to: "Cairo",
    typeOfTrip: "one way",
    passengerNumbers: "1",
    class: "economy",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "4:55AM",
    timeTo: "7:24AM",
    time: "2 hr 29 min",
    price: 419,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 114,
    from: "Cairo",
    to: "Dakhla Oasis",
    typeOfTrip: "round trip",
    passengerNumbers: "9",
    class: "premium",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "1:43PM",
    timeTo: "5:15PM",
    time: "3 hr 32 min",
    price: 330,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: "direct",
  },
  {
    id: 115,
    from: "Cairo",
    to: "Marsa Alam",
    typeOfTrip: "one way",
    passengerNumbers: "9",
    class: "economy",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "10:47PM",
    timeTo: "2:01AM",
    time: "3 hr 14 min",
    price: 443,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 116,
    from: "Luxor",
    to: "Dakhla Oasis",
    typeOfTrip: "one way",
    passengerNumbers: "1",
    class: "economy",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "4:54PM",
    timeTo: "6:07PM",
    time: "1 hr 13 min",
    price: 330,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: "direct",
  },
  {
    id: 117,
    from: "Alexandria",
    to: "Aswan",
    typeOfTrip: "one way",
    passengerNumbers: "6",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "8:18AM",
    timeTo: "9:49AM",
    time: "1 hr 31 min",
    price: 427,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: 1,
  },
  {
    id: 118,
    from: "Hurghada",
    to: "Sohag",
    typeOfTrip: "one way",
    passengerNumbers: "9",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "8:34AM",
    timeTo: "9:38AM",
    time: "1 hr 4 min",
    price: 558,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: 1,
  },
  {
    id: 119,
    from: "Marsa Alam",
    to: "Aswan",
    typeOfTrip: "one way",
    passengerNumbers: "3",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "10:34PM",
    timeTo: "12:00AM",
    time: "1 hr 26 min",
    price: 409,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: 1,
  },
  {
    id: 120,
    from: "Sohag",
    to: "Aswan",
    typeOfTrip: "round trip",
    passengerNumbers: "1",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "10:27PM",
    timeTo: "1:58AM",
    time: "3 hr 31 min",
    price: 494,
    vat: 14,
    airline: "Adeal",
    numberOfStops: 1,
  },
  {
    id: 121,
    from: "Alexandria",
    to: "Abu Simbel",
    typeOfTrip: "one way",
    passengerNumbers: "10",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "3:56PM",
    timeTo: "5:32PM",
    time: "1 hr 36 min",
    price: 351,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: 1,
  },
  {
    id: 122,
    from: "Port Said",
    to: "Aswan",
    typeOfTrip: "round trip",
    passengerNumbers: "5",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "5:19PM",
    timeTo: "8:27PM",
    time: "3 hr 8 min",
    price: 307,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: 1,
  },
  {
    id: 123,
    from: "Cairo",
    to: "Alexandria",
    typeOfTrip: "round trip",
    passengerNumbers: "4",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "10:12AM",
    timeTo: "12:32PM",
    time: "2 hr 20 min",
    price: 354,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 124,
    from: "Hurghada",
    to: "Marsa Alam",
    typeOfTrip: "one way",
    passengerNumbers: "7",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "1:33PM",
    timeTo: "2:51PM",
    time: "1 hr 18 min",
    price: 503,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: "direct",
  },
  {
    id: 125,
    from: "Alexandria",
    to: "Sohag",
    typeOfTrip: "one way",
    passengerNumbers: "4",
    class: "economy",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "2:29PM",
    timeTo: "6:01PM",
    time: "3 hr 32 min",
    price: 591,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: "direct",
  },
  {
    id: 126,
    from: "Abu Simbel",
    to: "Aswan",
    typeOfTrip: "one way",
    passengerNumbers: "7",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "3:59AM",
    timeTo: "6:07AM",
    time: "2 hr 8 min",
    price: 365,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: 1,
  },
  {
    id: 127,
    from: "Sharm El Sheikh",
    to: "Taba",
    typeOfTrip: "round trip",
    passengerNumbers: "8",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "8:24AM",
    timeTo: "11:25AM",
    time: "3 hr 1 min",
    price: 575,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 128,
    from: "Cairo",
    to: "Sharm El Sheikh",
    typeOfTrip: "round trip",
    passengerNumbers: "2",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "8:08AM",
    timeTo: "12:00PM",
    time: "3 hr 52 min",
    price: 444,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: "direct",
  },
  {
    id: 129,
    from: "Dakhla Oasis",
    to: "Hurghada",
    typeOfTrip: "round trip",
    passengerNumbers: "3",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "10:15PM",
    timeTo: "1:09AM",
    time: "2 hr 54 min",
    price: 436,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: "direct",
  },
  {
    id: 130,
    from: "Sharm El Sheikh",
    to: "Marsa Alam",
    typeOfTrip: "round trip",
    passengerNumbers: "5",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "8:57PM",
    timeTo: "12:36AM",
    time: "3 hr 39 min",
    price: 363,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: 1,
  },
  {
    id: 131,
    from: "Sohag",
    to: "Sharm El Sheikh",
    typeOfTrip: "round trip",
    passengerNumbers: "1",
    class: "premium",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "10:33PM",
    timeTo: "12:50AM",
    time: "2 hr 17 min",
    price: 575,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: "direct",
  },
  {
    id: 132,
    from: "Port Said",
    to: "Sohag",
    typeOfTrip: "one way",
    passengerNumbers: "9",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "8:28PM",
    timeTo: "10:01PM",
    time: "1 hr 33 min",
    price: 483,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: "direct",
  },
  {
    id: 133,
    from: "Sohag",
    to: "Dakhla Oasis",
    typeOfTrip: "one way",
    passengerNumbers: "2",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "6:28AM",
    timeTo: "8:57AM",
    time: "2 hr 29 min",
    price: 386,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: 1,
  },
  {
    id: 134,
    from: "Dakhla Oasis",
    to: "Cairo",
    typeOfTrip: "round trip",
    passengerNumbers: "5",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "12:43PM",
    timeTo: "3:50PM",
    time: "3 hr 7 min",
    price: 353,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 135,
    from: "Dakhla Oasis",
    to: "Abu Simbel",
    typeOfTrip: "round trip",
    passengerNumbers: "10",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "1:00AM",
    timeTo: "4:09AM",
    time: "3 hr 9 min",
    price: 523,
    vat: 14,
    airline: "Adeal",
    numberOfStops: 1,
  },
  {
    id: 136,
    from: "Alexandria",
    to: "Abu Simbel",
    typeOfTrip: "one way",
    passengerNumbers: "10",
    class: "business",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "5:45AM",
    timeTo: "6:59AM",
    time: "1 hr 14 min",
    price: 380,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: 1,
  },
  {
    id: 137,
    from: "Dakhla Oasis",
    to: "Aswan",
    typeOfTrip: "round trip",
    passengerNumbers: "1",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "6:01PM",
    timeTo: "7:27PM",
    time: "1 hr 26 min",
    price: 392,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: 1,
  },
  {
    id: 138,
    from: "Dakhla Oasis",
    to: "Taba",
    typeOfTrip: "one way",
    passengerNumbers: "3",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "12:38AM",
    timeTo: "3:32AM",
    time: "2 hr 54 min",
    price: 599,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: 1,
  },
  {
    id: 139,
    from: "Marsa Alam",
    to: "Port Said",
    typeOfTrip: "round trip",
    passengerNumbers: "10",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "12:58AM",
    timeTo: "2:27AM",
    time: "1 hr 29 min",
    price: 354,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: 1,
  },
  {
    id: 140,
    from: "Marsa Alam",
    to: "Luxor",
    typeOfTrip: "round trip",
    passengerNumbers: "7",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "2:43PM",
    timeTo: "5:05PM",
    time: "2 hr 22 min",
    price: 382,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: 1,
  },
  {
    id: 141,
    from: "El Arish",
    to: "Sohag",
    typeOfTrip: "one way",
    passengerNumbers: "7",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "5:10AM",
    timeTo: "6:34AM",
    time: "1 hr 24 min",
    price: 433,
    vat: 14,
    airline: "Adeal",
    numberOfStops: 1,
  },
  {
    id: 142,
    from: "Luxor",
    to: "Taba",
    typeOfTrip: "one way",
    passengerNumbers: "6",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "9:06AM",
    timeTo: "11:45AM",
    time: "2 hr 39 min",
    price: 460,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: 1,
  },
  {
    id: 143,
    from: "Abu Simbel",
    to: "Sharm El Sheikh",
    typeOfTrip: "one way",
    passengerNumbers: "3",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "8:47PM",
    timeTo: "11:58PM",
    time: "3 hr 11 min",
    price: 592,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: 1,
  },
  {
    id: 144,
    from: "Taba",
    to: "Abu Simbel",
    typeOfTrip: "round trip",
    passengerNumbers: "1",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "9:52PM",
    timeTo: "12:18AM",
    time: "2 hr 26 min",
    price: 590,
    vat: 14,
    airline: "Adeal",
    numberOfStops: 1,
  },
  {
    id: 145,
    from: "Abu Simbel",
    to: "Taba",
    typeOfTrip: "round trip",
    passengerNumbers: "2",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "5:39PM",
    timeTo: "9:12PM",
    time: "3 hr 33 min",
    price: 596,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: "direct",
  },
  {
    id: 146,
    from: "Hurghada",
    to: "Sohag",
    typeOfTrip: "round trip",
    passengerNumbers: "3",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "11:30PM",
    timeTo: "1:06AM",
    time: "1 hr 36 min",
    price: 549,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 147,
    from: "El Arish",
    to: "Sohag",
    typeOfTrip: "round trip",
    passengerNumbers: "8",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "12:01AM",
    timeTo: "1:05AM",
    time: "1 hr 4 min",
    price: 378,
    vat: 14,
    airline: "Adeal",
    numberOfStops: 1,
  },
  {
    id: 148,
    from: "El Arish",
    to: "Hurghada",
    typeOfTrip: "round trip",
    passengerNumbers: "1",
    class: "economy",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "2:09PM",
    timeTo: "4:05PM",
    time: "1 hr 56 min",
    price: 541,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: "direct",
  },
  {
    id: 149,
    from: "Dakhla Oasis",
    to: "Sohag",
    typeOfTrip: "one way",
    passengerNumbers: "3",
    class: "economy",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "7:11PM",
    timeTo: "8:41PM",
    time: "1 hr 30 min",
    price: 505,
    vat: 14,
    airline: "Adeal",
    numberOfStops: 1,
  },
  {
    id: 150,
    from: "Alexandria",
    to: "Cairo",
    typeOfTrip: "round trip",
    passengerNumbers: "3",
    class: "economy",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "8:34PM",
    timeTo: "12:15AM",
    time: "3 hr 41 min",
    price: 425,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 151,
    from: "Marsa Alam",
    to: "Abu Simbel",
    typeOfTrip: "round trip",
    passengerNumbers: "4",
    class: "premium",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "10:45PM",
    timeTo: "2:15AM",
    time: "3 hr 30 min",
    price: 430,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: 1,
  },
  {
    id: 152,
    from: "Taba",
    to: "Port Said",
    typeOfTrip: "one way",
    passengerNumbers: "7",
    class: "premium",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "5:06PM",
    timeTo: "7:36PM",
    time: "2 hr 30 min",
    price: 351,
    vat: 14,
    airline: "Adeal",
    numberOfStops: 1,
  },
  {
    id: 153,
    from: "Dakhla Oasis",
    to: "Aswan",
    typeOfTrip: "round trip",
    passengerNumbers: "8",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "1:21AM",
    timeTo: "4:09AM",
    time: "2 hr 48 min",
    price: 331,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: "direct",
  },
  {
    id: 154,
    from: "Sharm El Sheikh",
    to: "Dakhla Oasis",
    typeOfTrip: "one way",
    passengerNumbers: "7",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "9:29AM",
    timeTo: "11:03AM",
    time: "1 hr 34 min",
    price: 541,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 155,
    from: "Hurghada",
    to: "Aswan",
    typeOfTrip: "one way",
    passengerNumbers: "10",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "4:58PM",
    timeTo: "7:57PM",
    time: "2 hr 59 min",
    price: 539,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: 1,
  },
  {
    id: 156,
    from: "Cairo",
    to: "Luxor",
    typeOfTrip: "round trip",
    passengerNumbers: "1",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "5:26PM",
    timeTo: "6:31PM",
    time: "1 hr 5 min",
    price: 464,
    vat: 14,
    airline: "Adeal",
    numberOfStops: 1,
  },
  {
    id: 157,
    from: "Sharm El Sheikh",
    to: "Aswan",
    typeOfTrip: "one way",
    passengerNumbers: "1",
    class: "economy",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "1:41AM",
    timeTo: "4:42AM",
    time: "3 hr 1 min",
    price: 539,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: 1,
  },
  {
    id: 158,
    from: "Marsa Alam",
    to: "El Arish",
    typeOfTrip: "one way",
    passengerNumbers: "5",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "4:00PM",
    timeTo: "6:57PM",
    time: "2 hr 57 min",
    price: 457,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: "direct",
  },
  {
    id: 159,
    from: "Alexandria",
    to: "Abu Simbel",
    typeOfTrip: "one way",
    passengerNumbers: "10",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "7:55PM",
    timeTo: "9:01PM",
    time: "1 hr 6 min",
    price: 343,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: 1,
  },
  {
    id: 160,
    from: "Marsa Alam",
    to: "Taba",
    typeOfTrip: "round trip",
    passengerNumbers: "2",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "7:29PM",
    timeTo: "10:37PM",
    time: "3 hr 8 min",
    price: 377,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: 1,
  },
  {
    id: 161,
    from: "El Arish",
    to: "Marsa Alam",
    typeOfTrip: "one way",
    passengerNumbers: "10",
    class: "premium",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "4:10PM",
    timeTo: "5:50PM",
    time: "1 hr 40 min",
    price: 360,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: 1,
  },
  {
    id: 162,
    from: "Abu Simbel",
    to: "Hurghada",
    typeOfTrip: "round trip",
    passengerNumbers: "3",
    class: "economy",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "2:51AM",
    timeTo: "6:12AM",
    time: "3 hr 21 min",
    price: 411,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 163,
    from: "Abu Simbel",
    to: "Port Said",
    typeOfTrip: "round trip",
    passengerNumbers: "4",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "2:43PM",
    timeTo: "6:37PM",
    time: "3 hr 54 min",
    price: 380,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 164,
    from: "El Arish",
    to: "Marsa Alam",
    typeOfTrip: "round trip",
    passengerNumbers: "9",
    class: "economy",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "4:33PM",
    timeTo: "6:21PM",
    time: "1 hr 48 min",
    price: 382,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: 1,
  },
  {
    id: 165,
    from: "Sohag",
    to: "Alexandria",
    typeOfTrip: "round trip",
    passengerNumbers: "4",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "11:28AM",
    timeTo: "2:49PM",
    time: "3 hr 21 min",
    price: 387,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: "direct",
  },
  {
    id: 166,
    from: "Aswan",
    to: "Taba",
    typeOfTrip: "one way",
    passengerNumbers: "2",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "3:57PM",
    timeTo: "7:02PM",
    time: "3 hr 5 min",
    price: 312,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: "direct",
  },
  {
    id: 167,
    from: "Alexandria",
    to: "Sharm El Sheikh",
    typeOfTrip: "round trip",
    passengerNumbers: "1",
    class: "premium",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "9:31AM",
    timeTo: "11:35AM",
    time: "2 hr 4 min",
    price: 347,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: 1,
  },
  {
    id: 168,
    from: "Alexandria",
    to: "El Arish",
    typeOfTrip: "round trip",
    passengerNumbers: "5",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "3:50PM",
    timeTo: "5:32PM",
    time: "1 hr 42 min",
    price: 372,
    vat: 14,
    airline: "Adeal",
    numberOfStops: 1,
  },
  {
    id: 169,
    from: "Taba",
    to: "Sharm El Sheikh",
    typeOfTrip: "round trip",
    passengerNumbers: "10",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "4:42PM",
    timeTo: "7:46PM",
    time: "3 hr 4 min",
    price: 301,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: 1,
  },
  {
    id: 170,
    from: "Alexandria",
    to: "Hurghada",
    typeOfTrip: "one way",
    passengerNumbers: "2",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "12:31PM",
    timeTo: "4:07PM",
    time: "3 hr 36 min",
    price: 530,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: 1,
  },
  {
    id: 171,
    from: "Abu Simbel",
    to: "Taba",
    typeOfTrip: "round trip",
    passengerNumbers: "2",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "9:31PM",
    timeTo: "12:57AM",
    time: "3 hr 26 min",
    price: 516,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: "direct",
  },
  {
    id: 172,
    from: "Marsa Alam",
    to: "Luxor",
    typeOfTrip: "round trip",
    passengerNumbers: "3",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "6:48AM",
    timeTo: "8:10AM",
    time: "1 hr 22 min",
    price: 511,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 173,
    from: "Port Said",
    to: "Marsa Alam",
    typeOfTrip: "one way",
    passengerNumbers: "1",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "2:59AM",
    timeTo: "4:21AM",
    time: "1 hr 22 min",
    price: 495,
    vat: 14,
    airline: "Adeal",
    numberOfStops: 1,
  },
  {
    id: 174,
    from: "Dakhla Oasis",
    to: "Marsa Alam",
    typeOfTrip: "one way",
    passengerNumbers: "3",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "5:55AM",
    timeTo: "7:28AM",
    time: "1 hr 33 min",
    price: 370,
    vat: 14,
    airline: "Adeal",
    numberOfStops: 1,
  },
  {
    id: 175,
    from: "Port Said",
    to: "Dakhla Oasis",
    typeOfTrip: "round trip",
    passengerNumbers: "9",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "3:46AM",
    timeTo: "7:05AM",
    time: "3 hr 19 min",
    price: 317,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: 1,
  },
  {
    id: 176,
    from: "Port Said",
    to: "Hurghada",
    typeOfTrip: "round trip",
    passengerNumbers: "10",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "9:57AM",
    timeTo: "1:19PM",
    time: "3 hr 22 min",
    price: 365,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: "direct",
  },
  {
    id: 177,
    from: "Aswan",
    to: "Alexandria",
    typeOfTrip: "one way",
    passengerNumbers: "4",
    class: "premium",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "3:17AM",
    timeTo: "6:38AM",
    time: "3 hr 21 min",
    price: 488,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: 1,
  },
  {
    id: 178,
    from: "Dakhla Oasis",
    to: "Marsa Alam",
    typeOfTrip: "round trip",
    passengerNumbers: "9",
    class: "business",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "3:48PM",
    timeTo: "5:31PM",
    time: "1 hr 43 min",
    price: 427,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: "direct",
  },
  {
    id: 179,
    from: "Dakhla Oasis",
    to: "El Arish",
    typeOfTrip: "round trip",
    passengerNumbers: "2",
    class: "business",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "8:10PM",
    timeTo: "10:14PM",
    time: "2 hr 4 min",
    price: 461,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: "direct",
  },
  {
    id: 180,
    from: "Marsa Alam",
    to: "Aswan",
    typeOfTrip: "one way",
    passengerNumbers: "10",
    class: "business",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "5:06PM",
    timeTo: "8:15PM",
    time: "3 hr 9 min",
    price: 488,
    vat: 14,
    airline: "Adeal",
    numberOfStops: 1,
  },
  {
    id: 181,
    from: "Dakhla Oasis",
    to: "Alexandria",
    typeOfTrip: "round trip",
    passengerNumbers: "10",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "3:17PM",
    timeTo: "7:01PM",
    time: "3 hr 44 min",
    price: 346,
    vat: 14,
    airline: "Adeal",
    numberOfStops: 1,
  },
  {
    id: 182,
    from: "Port Said",
    to: "Dakhla Oasis",
    typeOfTrip: "round trip",
    passengerNumbers: "2",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "5:58AM",
    timeTo: "9:26AM",
    time: "3 hr 28 min",
    price: 558,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: "direct",
  },
  {
    id: 183,
    from: "Dakhla Oasis",
    to: "Abu Simbel",
    typeOfTrip: "round trip",
    passengerNumbers: "9",
    class: "economy",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "5:24PM",
    timeTo: "9:09PM",
    time: "3 hr 45 min",
    price: 413,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: 1,
  },
  {
    id: 184,
    from: "Dakhla Oasis",
    to: "Marsa Alam",
    typeOfTrip: "round trip",
    passengerNumbers: "9",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "1:56PM",
    timeTo: "4:35PM",
    time: "2 hr 39 min",
    price: 568,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: 1,
  },
  {
    id: 185,
    from: "Taba",
    to: "Port Said",
    typeOfTrip: "round trip",
    passengerNumbers: "8",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "9:58PM",
    timeTo: "11:21PM",
    time: "1 hr 23 min",
    price: 510,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: 1,
  },
  {
    id: 186,
    from: "Taba",
    to: "Aswan",
    typeOfTrip: "one way",
    passengerNumbers: "10",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "4:55PM",
    timeTo: "8:43PM",
    time: "3 hr 48 min",
    price: 485,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: 1,
  },
  {
    id: 187,
    from: "Port Said",
    to: "Sharm El Sheikh",
    typeOfTrip: "round trip",
    passengerNumbers: "8",
    class: "first",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "7:00PM",
    timeTo: "8:59PM",
    time: "1 hr 59 min",
    price: 307,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: "direct",
  },
  {
    id: 188,
    from: "Dakhla Oasis",
    to: "Taba",
    typeOfTrip: "one way",
    passengerNumbers: "4",
    class: "business",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "6:17AM",
    timeTo: "9:41AM",
    time: "3 hr 24 min",
    price: 571,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 189,
    from: "Aswan",
    to: "Taba",
    typeOfTrip: "round trip",
    passengerNumbers: "5",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "8:21AM",
    timeTo: "10:57AM",
    time: "2 hr 36 min",
    price: 590,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 190,
    from: "Aswan",
    to: "Cairo",
    typeOfTrip: "round trip",
    passengerNumbers: "1",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "3:52PM",
    timeTo: "7:41PM",
    time: "3 hr 49 min",
    price: 389,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: "direct",
  },
  {
    id: 191,
    from: "Port Said",
    to: "Taba",
    typeOfTrip: "round trip",
    passengerNumbers: "6",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "9:55PM",
    timeTo: "11:29PM",
    time: "1 hr 34 min",
    price: 452,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 192,
    from: "Sharm El Sheikh",
    to: "Aswan",
    typeOfTrip: "round trip",
    passengerNumbers: "9",
    class: "premium",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "6:04AM",
    timeTo: "7:32AM",
    time: "1 hr 28 min",
    price: 418,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: "direct",
  },
  {
    id: 193,
    from: "Abu Simbel",
    to: "Dakhla Oasis",
    typeOfTrip: "one way",
    passengerNumbers: "7",
    class: "economy",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "2:21PM",
    timeTo: "5:33PM",
    time: "3 hr 12 min",
    price: 412,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 194,
    from: "Sohag",
    to: "Marsa Alam",
    typeOfTrip: "round trip",
    passengerNumbers: "9",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "2:21AM",
    timeTo: "4:16AM",
    time: "1 hr 55 min",
    price: 388,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: "direct",
  },
  {
    id: 195,
    from: "Sharm El Sheikh",
    to: "Alexandria",
    typeOfTrip: "one way",
    passengerNumbers: "5",
    class: "economy",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "1:18PM",
    timeTo: "2:33PM",
    time: "1 hr 15 min",
    price: 413,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 196,
    from: "Marsa Alam",
    to: "Port Said",
    typeOfTrip: "round trip",
    passengerNumbers: "8",
    class: "economy",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "11:20AM",
    timeTo: "1:07PM",
    time: "1 hr 47 min",
    price: 527,
    vat: 14,
    airline: "Air-Arabia",
    numberOfStops: "direct",
  },
  {
    id: 197,
    from: "Cairo",
    to: "Sharm El Sheikh",
    typeOfTrip: "round trip",
    passengerNumbers: "8",
    class: "economy",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "4:19PM",
    timeTo: "7:55PM",
    time: "3 hr 36 min",
    price: 412,
    vat: 14,
    airline: "Saudia-Fly",
    numberOfStops: 1,
  },
  {
    id: 198,
    from: "Sohag",
    to: "Marsa Alam",
    typeOfTrip: "one way",
    passengerNumbers: "9",
    class: "economy",
    seat: "",
    bagWeight: "30kg",
    timeFrom: "1:11PM",
    timeTo: "4:11PM",
    time: "3 hr 0 min",
    price: 511,
    vat: 14,
    airline: "Adeal",
    numberOfStops: "direct",
  },
  {
    id: 199,
    from: "Aswan",
    to: "Dakhla Oasis",
    typeOfTrip: "round trip",
    passengerNumbers: "9",
    class: "business",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "2:39AM",
    timeTo: "5:41AM",
    time: "3 hr 2 min",
    price: 300,
    vat: 14,
    airline: "Oman-air",
    numberOfStops: "direct",
  },
  {
    id: 200,
    from: "Abu Simbel",
    to: "Luxor",
    typeOfTrip: "one way",
    passengerNumbers: "10",
    class: "first",
    seat: "",
    bagWeight: "20kg",
    timeFrom: "7:10AM",
    timeTo: "10:57AM",
    time: "3 hr 47 min",
    price: 408,
    vat: 14,
    airline: "Egypt-air",
    numberOfStops: "direct",
  },
];
